name: ml-notebooks
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.3
  - pip=19.1.1

  - cudatoolkit=10.0.130

  - numpy=1.16.4
  - pytorch=1.1.0
  - scikit-learn=0.21.2
  - torchvision=0.3.0

  - jupyter=1.0.0
  - matplotlib=3.1.0
  - pandas=0.25.0

  - pip:
    - torchtext==0.3.1
