name: ml-notebooks
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.3
  - pip=19.1.1

  - cudatoolkit=10.0.130

  - numpy=1.16.4
  - scikit-learn=0.21.2
  - pytorch=1.3.0
  - torchtext=0.4.0
  - torchvision=0.4.1

  - jupyter=1.0.0
  - matplotlib=3.1.0
  - pandas=0.25.0

