name: ml-experiments-gpu
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6.8
 
  - cudatoolkit=10.0.130

  - pytorch=1.0.1
  - torchvision=0.2.1
  - numpy=1.15.4

  - scikit-learn=0.20.2
  - scikit-image=0.14.1

  - jupyter=1.0.0
  - matplotlib=3.0.2
