name: ml-experiments-gpu
dependencies:
  - python=3.6.7

  - cudatoolkit=9.2-0
  - cudnn=7.3.1

  - tensorflow-gpu=1.12.0
  - scikit-learn=0.20.1
  - scikit-image=0.14.1

  - jupyter=1.0.0
  - matplotlib=3.0.1
