name: ml-pytorch
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.3

  - cudatoolkit=10.0.130

  - pytorch=1.1.0
  - torchvision=0.3.0
  - numpy=1.16.4

  - scikit-learn=0.21.2

  - jupyter=1.0.0=py37_7
  - matplotlib=3.1.0
